### ISSUE TITLE
问一个问题暗水印截图能不能解出

### ISSUE THREAD

**Issue by wanghaibao123** [hyyz3293/DarkWatermark#1]

**Comment by hyyz3293** [comment]
额， 截图肯定不行撒。截图是新生成的一张图了

**Comment by hyyz3293** [comment]
> _没有提供描述。_
额，截图肯定不行撒。截图是新生成的一张图了

**Comment by wanghaibao123** [comment]
> > _没有提供描述。_
> > 额，截图肯定不行撒。截图是新生成的一张图了



> > _没有提供描述。_
> > 额，截图肯定不行撒。截图是新生成的一张图了

**Comment by wanghaibao123** [comment]
老哥，我看网上说可以的哩，能不能帮忙试一下哩，我这边配置通不过

**Comment by hyyz3293** [comment]
> 老哥，我看网上说可以的哩，能不能帮忙试一下哩，我这边配置通不过

不行的，兄弟  配置还是很好整的，百度应该写的比我详细

**Comment by wanghaibao123** [comment]
好的谢谢

**Comment by hyyz3293** [comment]
> 好的谢谢

没事儿，一起学习
